# Uncomment this line to define a global platform for your project

platform :ios, '9.0'
inhibit_all_warnings! 

target 'LKKit' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LKKit
    pod 'Masonry',:inhibit_warnings => true
    pod 'YYKit',:inhibit_warnings => true
    pod 'pop', '~> 1.0.9',:inhibit_warnings => true
    pod 'CAAnimationBlocks', '~> 0.0.1',:inhibit_warnings => true
    pod 'RBBAnimation', '~> 0.4.0',:inhibit_warnings => true
    pod 'SVProgressHUD', '~> 2.0.3',:inhibit_warnings => true
end
